name: Allisyn the Editor

description: Allisyn the Editor

disqus: allisyntheeditor

google_analytics: UA-62746171-1

url: allisyntheeditor.com

markdown: redcarpet
permalink: /:title/

gems:
  - jekyll-sitemap

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
